### ISSUE TITLE
Couldn't know what slice it will land

### ISSUE THREAD

**Issue by gauuni** [tapptitude/TTFortuneWheel-iOS#1]
HI, I really love your project.
But there's still somethings I don't understand. Please show me.

1.  I'm using function `startAnimating(fininshIndex:Int = 0, _ completion:((Bool) -> Void)?)` but it didn;t land on right slice and landing on just same slice everytime
2. How to customize where the needle is? I would like the need will be in the middle of wheel.

Thanks alot

**Comment by EfraimB** [comment]
Hello gauuni, Thanks for your feedback.
1. By default the first index corresponds with the slice whose texts is written horizontally at 180 angle. The indexes of the slice will remain the same and do not change by rotating the wheel. So by calling `open func startAnimating(finishIndex: completion)` with the same index multiple times you will end up on the same slice every time.  

2. You can edit where the initial slice is drawn by setting `initialDrawingOffset`. If you want the needle to be in the middle of the wheel you have to offset the initial slice by 90 hence you have to set `initialDrawingOffset` to 90.0.

**Comment by EfraimB** [comment]
Hello gauuni, Thanks for your feedback.
1. By default the first index corresponds with the slice whose texts is written horizontally at 0 angle. The indexes of the slice will remain the same and do not change by rotating the wheel. So by calling `open func startAnimating(finishIndex: completion)` with the same index multiple times you will end up on the same slice every time.  

2. You can edit where the initial slice is drawn by setting `initialDrawingOffset`. If you want the needle to be in the middle of the wheel you have to offset the initial slice by 90 hence you have to set `initialDrawingOffset` to 90.0.

**Comment by gauuni** [comment]
I’m appreciate that
And one more thing. Could we make vertical text like this. The vertical one, not horizontal



--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Best regards,

 
Nguyen Khoi Nguyen 

Phone: +8401227513733

SkypeID: khoinguyeniosdev

**Comment by EfraimB** [comment]
Hi, We currently support only horizontal text but can add that in a future update. Please open another issue on this one. Thank you!

**Comment by NiravDiff** [comment]
@EfraimB I have checked your lib it was awesome but I haven't able to get the winning slice index and found this issue but don't get your above answer can you please care to explain it little bit more may be example is better.

Thank You!

**Comment by minhtuongitc** [comment]
I change it in view did load: 
spinningWheel.initialDrawingOffset = 90

:D
