### ISSUE TITLE
Need To wheel spin in different speed Slow and Fast

### ISSUE THREAD

**Issue by pchirag** [tapptitude/TTFortuneWheel-iOS#11]
i have to spin wheel in different spin but i face issues when it slow down its not work smooth plz help me about this issues.

**Comment by EfraimB** [comment]
You mean to have the wheel spin clockwise? Can you add some code that shows your attempt ? And maybe an image of the behavior ?

**Comment by pchirag** [comment]
i need to change wheel spinning speed slow and faster as per user define. 
currently wheel spin on only one speed that was fixed but i have to change rotating speed.

Hear is the link of video that i really want to do :- 
https://we.tl/NqlCRV7R04

**Comment by EfraimB** [comment]
```SpinningWheelAnimator``` class has two properties   ```fullRotationsUntilFinish:Int``` and
```rotationTime: CFTimeInterval```. Basically by decreasing the rotationTime and increasing the fullRotationUntilFinish you are increasing the speed in which the wheel is spinning.

**Comment by pchirag** [comment]
Hello i try to class two properties fullRotationsUntilFinish:Int and
rotationTime: CFTimeInterval.but when i spin it in slow speed before last spin its speed automatic increase. can you help me i need smooth animation while wheel have been stop.
