### ISSUE TITLE
Nice Work But background image

### ISSUE THREAD

**Issue by monang1611** [tapptitude/TTFortuneWheel-iOS#12]
your work is good but wants some customize like attach an image but I don't want to take slice image or color I want to put the full image on spin
can you help me, please?
![wheel 2x](https://user-images.githubusercontent.com/24529772/41807337-47315fd6-76eb-11e8-87da-257bd98c98f2.png)

**Comment by EfraimB** [comment]
Hi, basically you don't need the drawing of the wheel in slices and don't need the slices to be dynamic, right? In this case you don't need to use the ```TTFortuneWheel``` class, you only need the animator, that spins the wheel which is ```SpinningWheelAnimator```. You can initialize thin animator with ```init(withObjectToAnimate animationObject:SpinningAnimatorProtocol)```.
