### ISSUE TITLE
Code does not compile. Gives code sign error

### ISSUE THREAD

**Issue by JawaharChirimar** [tapptitude/TTFortuneWheel-iOS#14]
I followed the instructions to the pod and tried to compile the sample TTFortuneWheel in the git. The code does not compile. It gives a code sign error which I could not fix after spending 2 hours on it.

**Comment by EfraimB** [comment]
Hi Jawahar, are you trying to run the sample? you will have to provide you own unique bundle identifier in order to successfully run the example. If you want to integrate the library please use cocoapods or carthage
