### ISSUE TITLE
How sample app considering Ferris Wheel at 0 index.

### ISSUE THREAD

**Issue by aman198** [tapptitude/TTFortuneWheel-iOS#15]
Sample Code 
let slices = [ CarnivalWheelSlice.init(title: "0Roller Coaster"),
                       CarnivalWheelSlice.init(title: "1Try again"),
                       CarnivalWheelSlice.init(title: "2Free\nticket"),
                       CarnivalWheelSlice.init(title: "3Teddy\nbear"),
                       CarnivalWheelSlice.init(title: "4Large popcorn"),
                       CarnivalWheelSlice.init(title: "5Balloon figures"),
                       CarnivalWheelSlice.init(title: "6Ferris Wheel"),
                       CarnivalWheelSlice.init(title: "7Pony\nRide")]

Query : How sample app considering Ferris Wheel at 0 index. ?
Actually 0 index is Roller Coaster

**Comment by EfraimB** [comment]
Hello, The yellow pin on the wheel frame does not indicate 0 index, that is just in asset ( an image). By default, 0 index is the slice that has text written horizontally at 180 degrees from left to right. You can change which ever slice is the 0 index by setting `initialDrawingOffset`. (for instance  by setting initialDrawingOffset to 90 the Roller Coaster slice will be initially draw where no is drawn Free Thicket. Hope this helps you!
