### ISSUE TITLE
Rotate Title

### ISSUE THREAD

**Issue by thetay55** [tapptitude/TTFortuneWheel-iOS#16]
Hello,
I want to rotate horizontal title as picture
<img width="134" alt="screen shot 2018-08-27 at 11 30 28 am" src="https://user-images.githubusercontent.com/5179079/44640706-69130e80-a9ed-11e8-85b9-232b63161cff.png">

**Comment by EfraimB** [comment]
Hello we currently don't support rotating the titles but we'll consider it as a future update. Feel free to fork, add a feature and submit a pull request! Anyway you can add any additional graphic to slices ( this can be a rotated title for you). Please refer to this closed issue https://github.com/tapptitude/TTFortuneWheel-iOS/issues/2

**Comment by tuanph3012** [comment]
@thetay55 : Did you find a solution to rotate horizontal title ? Could you tell me how to do it?
