### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by inkl** [tapptitude/TTFortuneWheel-iOS#2]
Hi, is it possible to adding image or showing image instead of text?
Thanks a lot.

**Comment by EfraimB** [comment]
Hello, You can add any cg graphics to your slice by overriding this methods.  ` public func drawAdditionalGraphics(in context:CGContext, circularSegmentHeight:CGFloat,radius:CGFloat,sliceDegree:CGFloat)`. You can see a example on how we added the needle image in the slice implementation `FortuneWheelSliceImpl`. You will have to dynamically compute the radian position of the image using the provided parameters ( circularSegmentHeight,  radius, sliceDegree). Here is a graphic legend of all the properties https://gist.github.com/EfraimB/a43382a2360ae0311dd7823432578f94
