### ISSUE TITLE
CAMediaTimingFillMode

### ISSUE THREAD

**Issue by snc001** [tapptitude/TTFortuneWheel-iOS#21]
Hi Team,

I am currently getting this error after the MacOS mojave and Xcode 10 update.

- Type 'CAMediaTimingFillMode' (aka 'NSString') has no member 'forwards' - 

I am using the latest TTFortuneWheel libary... Any fix around this?

Best regards.

**Comment by aditya5045** [comment]
Any answers for this.

**Comment by EfraimB** [comment]
Hello, looks like you are trying to compile with an older version of swift. You either compile the library with 4.2 or user an older version of the library.

**Comment by pkmangukiya** [comment]
> Hi Team,
> 
> I am currently getting this error after the MacOS mojave and Xcode 10 update.
> 
> * Type 'CAMediaTimingFillMode' (aka 'NSString') has no member 'forwards' -
> 
> I am using the latest TTFortuneWheel libary... Any fix around this?
> 
> Best regards.

Replace :> animation.fillMode = kCAFillModeForwards

**Comment by pkmangukiya** [comment]
**animation.fillMode = kCAFillModeForwards**
