### ISSUE TITLE
Getting Multiple Errors (CAMediaTimingFillMode, NSAttributedString,  'CGRect' has no member 'inset')

### ISSUE THREAD

**Issue by Bhargavi-Enrich** [tapptitude/TTFortuneWheel-iOS#25]
Hi ,

I am using this library for iPhone, xCode: 9.4 and iOS>=10.0.

I am getting below errors when I install code using pods.

1. Use of unresolved identifier 'CAMediaTimingFillMode'
![screen shot 2018-11-05 at 5 09 31 pm](https://user-images.githubusercontent.com/44772308/47996197-bca48580-e11d-11e8-810c-3d02bab443ec.png)

2. 'Key' is not a member type of 'NSAttributedString'
![screen shot 2018-11-05 at 5 09 42 pm](https://user-images.githubusercontent.com/44772308/47996217-cf1ebf00-e11d-11e8-93c8-4d6f75bd98b2.png)

3. Value of type 'CGRect' has no member 'inset'
![screen shot 2018-11-05 at 5 08 57 pm](https://user-images.githubusercontent.com/44772308/47996234-db0a8100-e11d-11e8-93df-045a887082ba.png)

Can you please let me know if there is quick fix on this ?

Thanks.

**Comment by EfraimB** [comment]
Looks like you are using an older version of swift. Please use the corresponding version.
