### ISSUE TITLE
Orientation not supported

### ISSUE THREAD

**Issue by Vinod-kumar-ios** [tapptitude/TTFortuneWheel-iOS#27]
Orientation not supported , Two wheel designing if user change orientation.Please check screen shot attached . I am using in **collectionview cell**

![screenshot](https://user-images.githubusercontent.com/25063214/51107333-874e9f00-1814-11e9-96cb-deb838b1566e.png)

**Comment by EfraimB** [comment]
Can't quite understand that is the issue. Anyway you can force a redraw whenever you want by calling ```setNeedsDisplay()``` on the TTFortuneWheel view.

**Comment by EfraimB** [comment]
Fixed in 0.1.8. Thanks!
