### ISSUE TITLE
If there are only two slices in the array, it always fails.

### ISSUE THREAD

**Issue by Zedd0202** [tapptitude/TTFortuneWheel-iOS#3]
How should I fix it?

**Comment by EfraimB** [comment]
Hello, can send us the line of code where it does fail and what exception does it throw. Thanks!

**Comment by Zedd0202** [comment]
(Even if the grammar is not natural, please understand...:-)...)

Just a couple of slice arrays from the example source..
`let slices = [ CarnivalWheelSlice.init(title: "1"),
                       CarnivalWheelSlice.init(title: "2") ]`
Roulette can not choose. Once you run it, you will understand!!!!!! 
(And even when there are three slice arrays, they do not come exactly to the center.)

**Comment by EfraimB** [comment]
Just tried it and it works fine, with both 2 or 3 slices. Can tell us the line where it does crash?
![screen shot 2018-05-02 at 11 12 54 am](https://user-images.githubusercontent.com/17982613/39512469-cbb65862-4df9-11e8-818f-93c8bcbc6ae8.png)
![screen shot 2018-05-02 at 11 11 08 am](https://user-images.githubusercontent.com/17982613/39512470-cbd7770e-4df9-11e8-8214-a22c69f44a7d.png)
