### ISSUE TITLE
Replace slice title with images

### ISSUE THREAD

**Issue by Dhruv8015** [tapptitude/TTFortuneWheel-iOS#30]
Hello ,

I want to replace the slice title with images.

I referred your issue #2 , but can't get there.

Can you give me some more detail for #2 

How do we give context to the image ?

**Comment by EfraimB** [comment]
Hello, aside from what it's already mention in the referenced issue something that may help is to see how the image of the knob is added in the example in ```SpinningWheelSliceImpl.swift```  in the method ```public func drawAdditionalGraphics(in context:, circularSegmentHeight:,radius:,sliceDegree:)```
