### ISSUE TITLE
I need to add image along with title.

### ISSUE THREAD

**Issue by prashanthilucky** [tapptitude/TTFortuneWheel-iOS#34]
let slices = [ CarnivalWheelSlice.init(title: "Get 10 Unipay Ponits",spinImage:UIImage(named: "jackpot_icon.png")!),
                       CarnivalWheelSlice.init(title: "Get 10% Off",spinImage:UIImage(named: "jackpot_icon.png")!),
                       CarnivalWheelSlice.init(title: "Better Luck",spinImage:UIImage(named: "jackpot_icon.png")!),
                       CarnivalWheelSlice.init(title: "Spin Again",spinImage:UIImage(named: "jackpot_icon.png")!),
                       CarnivalWheelSlice.init(title: "Get 5 Unipay Points",spinImage:UIImage(named: "jackpot_icon.png")!),
                       CarnivalWheelSlice.init(title: "Get 5% Off",spinImage:UIImage(named: "jackpot_icon.png")!)]

**Comment by EfraimB** [comment]
Hello, please take a look at https://github.com/tapptitude/TTFortuneWheel-iOS/issues/2
