### ISSUE TITLE
Title position  

### ISSUE THREAD

**Issue by maheshm504** [tapptitude/TTFortuneWheel-iOS#35]
Hi At first I like the code and its very good

I need something like the label degree
Like currently 

label displays in straight Left side of wheel
reverse side in right side of wheel

I need that to be opposite 
<img width="490" alt="Screenshot 2019-11-30 at 10 26 37 AM" src="https://user-images.githubusercontent.com/13049637/69895788-134db480-135c-11ea-942a-5d636ba0fa30.png">
How can I do that can you help me on this ?

**Comment by EfraimB** [comment]
Hello, this feature is implemented in version 0.1.8. Just add ```spinningWheel.titleRotation = CGFloat.pi``` in ```viewDidLoad()```.

**Comment by maheshm504** [comment]
Thats awesome 
Thanks! Bro
