### ISSUE TITLE
Adding Images to slices

### ISSUE THREAD

**Issue by BobDeKort** [tapptitude/TTFortuneWheel-iOS#4]
Hello there, 

Really like the fortune wheel library and I would like to add images to the slices.
Do I use the "drawAdditionalGraphics" function and if so how would I use it?

Thanks in advance!

**Comment by EfraimB** [comment]
Hello Bob, 
Yes, exactly, please refer to this issue https://github.com/tapptitude/TTFortuneWheel-iOS/issues/2
