### ISSUE TITLE
Winning at the top of the wheel

### ISSUE THREAD

**Issue by snc001** [tapptitude/TTFortuneWheel-iOS#7]
Hi guys,

I was wondering if there is a way to make the winning happen at the top of the wheel instead of it being at the bottom??

Thank you

**Comment by EfraimB** [comment]
Hi, 
You can specify the finish offset angle by setting ```open var initialDrawingOffset```. Default the finishing for the winning index is the bottom one. If you want to be the top, you may offest this by setting ```open var initialDrawingOffset``` to 180.0.
