### ISSUE TITLE
drawAdditionalGraphics example?

### ISSUE THREAD

**Issue by snc001** [tapptitude/TTFortuneWheel-iOS#8]
Hi I was wondering if there is an example on how to use this method?

drawAdditionalGraphics

**Comment by EfraimB** [comment]
Hello,
Sure, actually there is an implementation of this method in SpinningWheelSliceImpl.swift, used to draw the wheel needles for each slice. You can see more information about what the parameters you get mean and how to use them in this issue https://github.com/tapptitude/TTFortuneWheel-iOS/issues/2
