### ISSUE TITLE
Tried following the SpinningWheelSliceImpl

### ISSUE THREAD

**Issue by snc001** [tapptitude/TTFortuneWheel-iOS#9]
So I've tried implementing custom graphics.

`import Foundation
import TTFortuneWheel

public class WheelCustomiser : FortuneWheelSliceProtocol{
    
    public enum Style {
        case dark
        case light
    }
    
    public var title: String
    public var degree: CGFloat = 0.0
    
    public var backgroundColor: UIColor? {
        switch style {
        case .dark: return TTUtils.uiColor(from: 0x320A51)
        case .light: return UIColor.white
        }
    }
    
    public var fontColor: UIColor {
        switch style {
        case .dark: return UIColor.white
        case .light: return TTUtils.uiColor(from: 0x320A51)
        }
    }
    
    public var font: UIFont {
        return UIFont.systemFont(ofSize: fontSize, weight: .bold)
    }
    
    public var style:Style = .dark
    
    public init(title:String) {
        self.title = title
    }
    
    public convenience init(title:String, degree:CGFloat) {
        self.init(title:title)
        self.degree = degree
    }    
    public func drawAdditionalGraphics(in context:CGContext, circularSegmentHeight:CGFloat,radius:CGFloat,sliceDegree:CGFloat) {
        let image = UIImage(named: "spinBtn", in: Bundle.sw_frameworkBundle(), compatibleWith: nil)!
        let centerOffset = CGPoint(x: -64, y: 17)
        let additionalGraphicRect = CGRect(x: centerOffset.x, y: centerOffset.y, width: 12, height: 12)
        let additionalGraphicPath = UIBezierPath(rect: additionalGraphicRect)
        context.saveGState()
        additionalGraphicPath.addClip()
        context.scaleBy(x: 1, y: -1)
        context.draw(image.cgImage!, in: CGRect(x: additionalGraphicRect.minX, y: -additionalGraphicRect.minY, width: image.size.width, height: image.size.height), byTiling: true)
        context.restoreGState()
    }
}
`

I get the Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional Value.

Is there something that I'm doing wrong here? This class here is virtually identical to the SpinningWheelSliceImpl.swift apart from trying to add the image really...

**Comment by EfraimB** [comment]
What is the line of code where your app crashes?

**Comment by snc001** [comment]
this is the line  `    let image = UIImage(named: "spinBtn", in: Bundle.sw_frameworkBundle(), compatibleWith: nil)!`

this is inside the drawAdditionalGraphics

**Comment by EfraimB** [comment]
The problem is you are trying to load the image from the bundle of the library. ```in: Bundle.sw_frameworkBundle().``` You should load the image from the main bundle. Please let me know if that solves the problem.

**Comment by snc001** [comment]
sadly its the same issue this is what you mean yes?

`let image = UIImage(named: "spinBtn", in: Bundle.main, compatibleWith: nil)!`

**Comment by EfraimB** [comment]
This is not a problem connected to this library, I  guess it fails no matter where you put that line of code throughout your application , am I right? Make sure you have an image with that name in your assets folder.

**Comment by snc001** [comment]
I have made sure that I have an image with that name in the asset - though does it matter about what size the image should be??

The error no longer appears with another file that has an image thats 50x50 but now i can't see the image where the old circles use to be from the example "niddleImage".

Did I need to call something else?

**Comment by snc001** [comment]
Quick on one to add here - Is there a way to rotate the title to 90 degrees?

Sorry about all the hassles and I really am appreciate all your help so far champ =)

**Comment by snc001** [comment]
What is the biggest size image can this wheel handle for custom graphics? - I have a 50x50 but its not drawing the round circle correctly

**Comment by EfraimB** [comment]
There is no size limit, make sure you put the wanted size in ```let additionalGraphicRect = CGRect(x: centerOffset.x, y: centerOffset.y, width: 12, height: 12)``` because I see you left it at 12 witch is very small.

**Comment by EfraimB** [comment]
If you want to rotate the title your only option is to make a subclass of your own extending FortuneWheelLayer, and override the draw slice method. Here is the code that draws the title 

`   //// Title  Drawing
        let textRect = CGRect(x: (titleXValue - rotationOffset), y: (titleYPosition - rotationOffset), width: titleWidthValue, height: titleHeightValue)
        let textTextContent = slice.title`

 If you want to add a feature just create another ticket or you can expose this method yourself and submit a pull request. Thank you!

**Comment by snc001** [comment]
Cool I'll try that out thank you =)

I am trying to make it work this way:
![wheel example](https://user-images.githubusercontent.com/12015902/39915572-693330f6-555c-11e8-8e29-7bf1d49d17ed.png)

but reality is:
![simulator screen shot - iphone 8 plus - 2018-05-11 at 20 45 26](https://user-images.githubusercontent.com/12015902/39915591-725d853c-555c-11e8-8b60-beb0eed956cc.png)

I've tried all sorts of x and y placements for them... is there something I'm missing hence the image is drawn this way? This is meant to be a yellow dot :/

**Comment by EfraimB** [comment]
It looks like you left the image size to 12x12 same in the example, you have to give it a larger size to accommodate your image. See comment above about the image
